import os

from dotenv import load_dotenv

load_dotenv()
TOKEN = os.getenv("DISCORD_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL")

SEASON_NAME_MIN_LENGTH = 1
SEASON_NAME_MAX_LENGTH = 100
SEASON_CODE_MIN_LENGTH = 1
SEASON_CODE_MAX_LENGTH = 10
SEASON_TEAM_SIZE_MIN = 1
SEASON_TEAM_SIZE_MAX = 5
TEAM_NAME_MIN_LENGTH = 1
TEAM_NAME_MAX_LENGTH = 100
TEAM_CODE_MIN_LENGTH = 1
TEAM_CODE_MAX_LENGTH = 10
